
import abc
from typing import Protocol
from .visitor import uvm_visitor

class uvm_object(Protocol):

    @abc.abstractmethod
    def get_name(self) -> str: ...

    @abc.abstractmethod
    def set_name(self, name: str) -> None: ...

    @abc.abstractmethod
    def get_full_name(self) -> str: ...

    @abc.abstractmethod
    def get_inst_id(self) -> int: ...

    @abc.abstractmethod
    def get_inst_count(self) -> int: ...

    @abc.abstractmethod
    def sprint(self) -> str: ...

    @abc.abstractmethod
    def get_type_name(self) -> str: ...

    @abc.abstractmethod
    def create(self, name: str = "") -> "uvm_object": ...

    @abc.abstractmethod
    def clone(self) -> "uvm_object": ...

    @abc.abstractmethod
    def print(self) -> None: ...

    @abc.abstractmethod
    def convert2string(self) -> str: ...

    @abc.abstractmethod
    def record(self) -> None: ...

    @abc.abstractmethod
    def copy(self, rhs: "uvm_object") -> None: ...

    @abc.abstractmethod
    def compare(self, rhs: "uvm_object") -> bool: ...

    @abc.abstractmethod
    def set_int_local(self, name: str, value: int) -> None: ...

    @abc.abstractmethod
    def set_string_local(self, name: str, value: str) -> None: ...

    @abc.abstractmethod
    def set_object_local(self, name: str, value: "uvm_object") -> None: ...

    @abc.abstractmethod
    def pack(self) -> object: ...

    @abc.abstractmethod
    def unpack(self, val : object): ...

    @abc.abstractmethod
    def randomize(self): ...

    @abc.abstractmethod
    def reseed(self) -> None: ...

    @abc.abstractmethod
    def accept(self, v : uvm_visitor): ...
