#!/usr/bin/env python3
"""Fail when a published SystemVerilog object carries no description.

Two things can go wrong with a generated reference, and neither is visible in a
green build:

**A published object with no doc comment.** It renders as a signature and a
``[source]`` link. The page looks complete and says nothing.

**A source file that reaches no page.** ``doc/source/*.rst`` scopes its sections
with ``:files:`` patterns, which is what keeps the reference free of
hand-maintained symbol lists -- but a file matching no pattern is simply absent,
and Sphinx has no reason to mention it.

So this compares the parsed index against the built ``objects.inv``:

    ./scripts/check-sv-doc-coverage.py [--html doc/build/html] [--list]

Exit 0 when every published object is described and every tier-A file is
represented, 1 otherwise. ``--baseline N`` tolerates N undescribed objects, for
running the gate before the backlog is paid off; it still fails on an increase,
which is what stops the backlog growing.
"""

from __future__ import annotations

import argparse
import collections
import os
import sys
import zlib

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHARE = os.path.join("src", "hdl_if", "share")

#: Files parsed so the rest elaborates, but deliberately never published.
#: Each entry is a reason, not just a path -- "we do not document this" should
#: be a statement someone can disagree with in review.
TIER_B = {
    "dpi/pyhdl_dpi_imports.svh":
        "CPython's C API, declared to SystemVerilog. Not our API, and CPython "
        "documents it better. See sv_api.rst 'Direct API'.",
    "uvm/pyhdl_uvm_apis.svh":
        "Generated by `api-gen-sv` from hdl_if.uvm.wrap. Regenerating would "
        "discard any comment written here; the Python side is the reference. "
        "See uvm.rst 'The generated transport layer'.",
    "dpi/pyhdl_if_call_dpi.svh":
        "DPI *exports*: the C layer calls these to re-enter SystemVerilog. "
        "Not callable from user code, and their contract is the C side's.",
    "dpi/pyhdl_if_init.svh":
        "`__pyhdl_if_init`, run once from a package-level initializer.",
    "dpi/pyhdl_if_call_init.svh":
        "`__pyhdl_if_call_init`, run once from a package-level initializer.",
    "dpi/pyhdl_if_tlm_init.svh":
        "`__pyhdl_if_tlm_init`, run once from a package-level initializer.",
    "uvm/pyhdl_uvm.sv":
        "The package declaration itself: a list of `include directives. Its "
        "contents are documented, section by section, in uvm.rst.",
}

#: Kinds whose members are shown whether or not they are documented, because
#: they are the object's public face rather than its implementation.
ALWAYS_SHOWN = {"port", "parameter"}


def build_index():
    """Index the same build units ``doc/source/conf.py`` does."""
    from sphinx_systemverilog.model.index import build_index as _build

    dpi = os.path.join(REPO, SHARE, "dpi")
    uvm = os.path.join(REPO, SHARE, "uvm")
    uvm_lib = os.path.join(REPO, "packages", "uvm", "src")
    share = os.path.join(REPO, SHARE)

    units = [os.path.join(dpi, "pyhdl_if.sv")]
    if os.path.isfile(os.path.join(uvm_lib, "uvm_pkg.sv")):
        units = [
            os.path.join(uvm_lib, "uvm_pkg.sv"),
            os.path.join(dpi, "pyhdl_if.sv"),
            os.path.join(uvm, "pyhdl_uvm.sv"),
        ]
    units += [
        os.path.join(dpi, "tlm_hdl2hvl_fifo.sv"),
        os.path.join(dpi, "tlm_hvl2hdl_fifo.sv"),
        os.path.join(share, "pyhdl_if_reqrsp_fifo.sv"),
    ]
    return _build(
        source_dirs=[], build_units=units, doc_style="doxygen",
        include_dirs=[dpi, uvm, uvm_lib], defines={}, base_path=REPO,
        nodocs_policy="include", document_macros=True,
    )


def published(html_dir: str) -> set[str]:
    """Names of every ``sv:`` object in the built inventory."""
    path = os.path.join(html_dir, "objects.inv")
    if not os.path.isfile(path):
        sys.exit(f"no inventory at {path}; run `make html` in doc/ first")
    raw = open(path, "rb").read()
    for n in range(1, 6):
        try:
            body = zlib.decompress(raw.split(b"\n", n)[-1]).decode()
            break
        except Exception:
            continue
    else:
        sys.exit(f"cannot decompress {path}")
    names = set()
    for line in body.splitlines():
        parts = line.split(None, 4)
        if len(parts) >= 2 and parts[1].startswith("sv:"):
            names.add(parts[0])
    return names


def own_objects(index):
    """Every indexed object declared in this project's SystemVerilog."""
    seen, out = set(), []
    for root in index.roots:
        for obj in root.walk():
            if id(obj) in seen:
                continue
            seen.add(id(obj))
            path = str(obj.location.file) if obj.location else ""
            path = path.replace("\\", "/")
            if SHARE.replace(os.sep, "/") + "/" not in path:
                continue
            rel = path.split(SHARE.replace(os.sep, "/") + "/", 1)[1]
            out.append((rel, obj))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--html", default=os.path.join(REPO, "doc", "build", "html"))
    ap.add_argument("--baseline", type=int, default=0,
                    help="tolerate this many undescribed objects (default 0)")
    ap.add_argument("--list", action="store_true",
                    help="print every undescribed object, grouped by file")
    args = ap.parse_args()

    index = build_index()
    inventory = published(args.html)
    objects = own_objects(index)

    undescribed = collections.defaultdict(list)
    files_seen = collections.Counter()
    files_published = collections.Counter()

    for rel, obj in objects:
        files_seen[rel] += 1
        if rel in TIER_B:
            continue
        name = obj.qualified_name or obj.name
        if name not in inventory:
            continue                       # not published: scope, not coverage
        files_published[rel] += 1
        if obj.kind in ALWAYS_SHOWN or obj.is_documented:
            continue
        undescribed[rel].append(f"{obj.kind} {name}")

    total = sum(len(v) for v in undescribed.values())
    tier_a = {f for f in files_seen if f not in TIER_B}
    unreachable = sorted(f for f in tier_a if not files_published[f])

    print(f"published sv objects : {len(inventory)}")
    print(f"tier-A source files  : {len(tier_a)}  "
          f"({len(TIER_B)} excluded by policy)")
    print(f"undescribed          : {total}"
          + (f"  (baseline {args.baseline})" if args.baseline else ""))

    if args.list and undescribed:
        print()
        for rel in sorted(undescribed, key=lambda f: -len(undescribed[f])):
            print(f"  {rel}  ({len(undescribed[rel])})")
            for entry in undescribed[rel]:
                print(f"      {entry}")

    failed = False
    if total > args.baseline:
        print(f"\nFAIL: {total} published object(s) carry no description"
              f"{f', over the baseline of {args.baseline}' if args.baseline else ''}."
              "\n      Re-run with --list to see them.")
        failed = True
    elif args.baseline and total < args.baseline:
        print(f"\nNOTE: the backlog shrank to {total}; lower --baseline in CI "
              "to lock the gain in.")

    if unreachable:
        print("\nFAIL: these files reach no page -- they match no :files: "
              "pattern in doc/source/*.rst, so nothing they declare is "
              "published:")
        for rel in unreachable:
            print(f"      {rel}  ({files_seen[rel]} object(s))")
        failed = True

    if not failed:
        print("\nOK")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
